from enum import Enum

class ErrorCode(Enum):
    InvalidArguments = ">> Invalid Arguments"
    PathNotFound = ">> Path Not Found"
    CommandNotFound = ">> Command Not Found"
    DiscoverError = ">> Unable To Discover Devices"
    UnableToRunScan = ">> Unable To Run Scan"
    PortNotInRange = ">> Port Not In Range"
    ConnectionFailed = ">> Unable To Form Connection"
    HostnameNotFound = ">> Unable To Find Hostname"
    FileNotFound = ">> File Not Found In Path"
    UnableToExecuteFile = ">> Unable To Execute File"
    WebsiteNotFound = ">> Website Not Found"
    DirectoryNotFound = ">> Directory Not Found"
    SubprocessError = ">> Subprocess Called Process Error"
    KeyErrorConnection = ">> KeyError - Unable To Form Connection"
    ValueErrorInput = ">> Value Error"
    MaxTokenExceeded = ">> Max Token Lenght Exceeded"
    KBInterrupt = ">> Keyboard Interrupt"